/**
 * 
 *  The list must be cleaned further, but I don't have the patience to keep going
 *  I'm at the letter h
 *  Keep an eye on the words that are abbreviations but also words, like ham: hamster 
 */

const en_abbreviations = {
	ab: "abdominal muscle / abalone / abscess  ",
	ad: "advantage / advertisement",
	advert: "advertisement",
	addy: "email address",
	admin: "administrator / administration",
	afish: "aficionado  ",
	ag: "agriculture (informal)",
	aggro: "aggravation or aggression",
	"agit-prop": "agitational propaganda",
	alky: "an alcoholic",
	amp: "ampere / amphetamine / amplifier / amputation or amputee / ampoule / amplify  ",
	app: "application",
	arco: "arcology  ",
	argie: "Argentine, Argentinian",
	aspie: "Someone with Asperger syndrome",
	auto: "automobile / automatic",
	av: "avatar",
	avvie: "avatar",
	bennies: "benzedrine / benefits",
	bevvy: "beverage",
	bi: "bisexual ",
	bike: "bicycle",
	bio: "biology / biography",
	birks: "Birkenstocks",
	biz: "business ",
	ops: "operations",
	bod: "body",
	bookie: "bookmaker",
	bra: "brassiere",
	bread: "bread and honey",
	bro: "brother  ",
	bronc: "bronco",
	bronto: "Brontosaurus ",
	bud: "buddy",
	budgie: "budgerigar",
	bunk: "bunkum",
	cab: "Cabernet Sauvignon / cabriolet",
	caff: "café",
	cal: "calorie / California / Calcutta",
	cali: "California / Calcutta",
	cam: "camera / camouflage",
	camo: "camouflage",
	Can: "Canada or Canadian",
	cap: "captain / lie",
	caps: "capitals",
	carbs: "carbohydrates",
	cardio: "cardiovascular training",
	cat: "catalytic converter / catamaran",
	chem: "chemistry",
	chemo: "chemotherapy",
	Chevy: "Chevrolet",
	chimp: "chimpanzee",
	cig: "cigarette",
	cishet : "cisgender-heterosexual",
	civ: "civilization",
	civvy: "civilian",
	civvie: "civilian",
	civvies: "civilian clothes",
	clit: "clitoris",
	coed: "coeducational",
	coke: "cocaine",
	Coke: "Coca-Cola",
	com: "command / communication",
	combo: "combination",
	Commie: "Communist",
	con: "confidence trick / convention / convict",
	condo: "condominium",
	congrats: "congratulations",
	contacts: "contact lenses",
	"co-op": "cooperative",
	corp: "corporation",
	cred: "credibility",
	crip: "cripple",
	croc: "crocodile",
	curio: "curiosity",
	cuz: " cousin",
	cyber: "cybernetic ",
	decaf: "decaffeinated",
	decal: "decalcomania",
	decij: "decision",
	deco: "decoration",
	deets: "details",
	defrag: "defragment",
	deli: "delicatessen",
	delish: "delicious",
	Dem: "Democrat",
	demo: "demonstration / demolition",
	derm: "dermatologist / dermatological",
	depict: "depicture",
	detox: "detoxification",
	dicot: "dicotyledon",
	dif: "difference",
	diff: "difference",
	digi: "digital",
	cabes: "cable",
	dino: "dinosaur",
	dis: "disrespect",
	diss: "disrespect",
	disco: "discotheque",
	doc: "doctor / document",
	dorm: "dormitory",
	Dub: "Dubliner",
	"e-": "electronic ",
	ed: "education",
	emo: "emotional",
	ep: "episode",
	eppie: "epileptic seizure",
	eppy: "epileptic seizure",
	ex: "ex- / exhibition / war exercise",
	exam: "examination",
	exec: "executive",
	expo: "exposition",
	fab: "fabrication / fabulous",
	fan: "fanatic",
	fav: "favorite",
	fed: "federal",
	frack: "fracture",
	frag: "fragmentation grenade / kill",
	fridge: "refrigerator",
	ganj: "ganja",
	gas: "gasoline",
	gat: "Gatling gun",
	gig: "gigabyte",
	gin: "Geneva",
	glutes: "gluteus maximus",
	fig: "figure",
	gov: "governor / government",
	guv: "governor / government",
	grad: 'graduate (or graduation, as in "grad night")',
	gran: "grandmother",
	granny: "grandmother",
	guac: "guacamole",
	gym: "gymnasium",
	hammy: "hamster",
	hash: "hashish",
	hep: "hepatitis",
	"hetero or het": "heterosexual",
	hifi: "high fidelity system",
	"hi(gh) res": "high resolution",
	hippo: "hippopotamus",
	homo: "homosexual / homogenized (milk)",
	hydro: "hydroelectricity / hydrotherapy / hydrothermal / hydroponic",
	hype: "hyperbole",
	hypo: "hypodermic",
	hyper: "hyperactive",
	Inc: "Incorporated",
	"indie, indy": "independence, independent / independent music / independent film",
	"Indy 500": "Indianapolis 500",
	inf: "infinitely",
	info: "information",
	"infra dig": "infra dignitatem (beneath one's dignity) (borrowed from Latin)",
	inti: "intifada",
	intro: "introduction",
	ipecac: "ipecacuanha",
	Itey: "Italian (offensive)",
	Jap: "Japanese (offensive)",
	Jerry: "German (offensive, historical)",
	kilo: "kilogram",
	klepto: "kleptomaniac",
	lab: "laboratory / (cap.) Labrador retriever",
	"lav, lavvy": "lavatory",
	legit: "legitimate",
	"les, lez, or lesbo": "lesbian",
	lib: "liberal / liberation / library (computer science) / (cap.) Libertarian",
	"Lib-Lab": "Liberal-Labour (UK)",
	limo: "limousine",
	lino: "linoleum / Linotype machine",
	lit: "literature",
	"lit crit": "literary criticism",
	"lo-cal": "low-calorie",
	log: "logarithm",
	mac: "macadam / macaroni / (with initial capital) Apple Macintosh / McIntosh apple / (or mack) mackintosh",
	macro: "macroinstruction",
	mag: "magazine / magnet / magnification / magnesium alloy wheels / magnum",
	"Man United": "Manchester United F.C.",
	Mass: "Massachusetts",
	"maths (UK) or math (U.S.)": "mathematics",
	matric: "matriculation",
	max: "maximum",
	mayo: "mayonnaise",
	"med, meds":
		"medication / medic / (with initial capital) Mediterranean (the sea or the surrounding area)",
	meg: "megabyte",
	memo: "memorandum",
	meth: "methamphetamine",
	meths: "methylated spirits",
	"Mex or Mexi": "Mexican",
	mezc: "mescaline",
	"mike or mic": "microphone",
	mig: "milligram mg",
	mil: "military / millilitre",
	Minn: "Minnesota",
	Miss: "Mississippi",
	mod: "moderator / modern / modification / modular / modulo",
	mono: "monaural / monochrome / mononucleosis",
	monocot: "monocotyledon",
	movie: "feature film (i.e. moving picture)",
	natch: "naturally",
	neg: "negative",
	negs: "(photographic) negatives / negative hits",
	net: "Internet",
	neocon: "neoconservative",
	neolib: "neoliberal",
	Newfy: "Newfoundlander",
	Nip: "A Japanese (derogatory, Nipponese)",
	nympho: "nymphomaniac",
	op: "optical art / optical / operation / operator / opportunity",
	"op-ed": '"opposite the editorial (page)", possibly "Opinion-Editorial" page',
	orang: "orangutan",
	Paki: "Pakistani (pejorative)",
	"Paleo diet": "Paleolithic diet",
	pants: "pantaloons",
	"pap, paps": "paparazzi",
	pec: "pectoral muscle",
	peeps: "people  ",
	Peke: "Pekingese",
	Penn: "Pennsylvania",
	perk: "perquisite",
	perp: "perpetrator  ",
	perv: "pervert",
	photo: "photograph (informal)",
	"photo op": "photo(graphic) opportunity",
	"phys ed": "physical education (informal)",
	piano: "pianoforte",
	"pic (plural pics or pix)": "(motion) picture   / (photographic) picture  ",
	pol: "politician (informal)",
	polio: "poliomyelitis",
	poly: 'polyamorous / polyester / polyethylene / polygraph (U.S. government, as in "full scope poly") / polymer / Polynesian / polytechnic',
	"po-mo": "post-modern",
	pop: "popular (informal) / popular music",
	"porn or porno": "pornography  ",
	postgrad: "postgraduate",
	pram: "perambulator, a baby carriage",
	prefs: "preferences",
	preg: "pregnant",
	prelim: "preliminary (examination)",
	prep: "preparatory",
	"pres or prez": "president",
	pro: "professional",
	prof: "professor",
	prom: "promenade",
	promo: "promotion",
	prop: "propaganda / propeller / proposition / property (especially in theater sense)",
	psych: "psychology",
	psycho: "psychopath",
	pub: "publication / public house",
	pullie: "pullover",
	pulsar: "pulsating / star",
	pyro: "pyromaniac / pyrotechnic",
	quad: "quadrangle (courtyard) / quadruplet / quadriceps muscles / quadcopter (quad-engine helicopter) / quadbike (New Zealand)",
	"quin, quint (U.S. and Canada)": "quintuplet",
	rad: "radian / radiator / radical / (military) radio",
	radfem: "radical feminist",
	radio: "radiotelegraphy",
	"raspberry, razzy":
		"raspberry tart (fart; more commonly, the derisive sound made with the tongue and lips; a Bronx cheer)",
	rasp: "raspberry",
	Rasta: "Rastafarian",
	Reb: "Rebel (i.e., Confederate)",
	rec: "recreation / (all capital) record",
	"recon, reccy": "reconnaissance",
	ref: "referee / reference",
	reg: "registration (.mw-parser-output .IPA-label-small{font-size:85%}.mw-parser-output .references .IPA-label-small,.mw-parser-output .infobox .IPA-label-small,.mw-parser-output .navbox .IPA-label-small{font-size:100%}UK: /ˈrɛdʒ/, of a motor vehicle) / regulation /ˈrɛɡ/",
	rehab: "rehabilitation",
	rep: "repetition / representative / (with initial capital) Republican / reputation",
	repo: "repossession / repo man – repossession person",
	res: "reserve (Indian or military) / residence / resolution",
	resp: "respiratory",
	retro: "retro-rocket / retrospective",
	rev: "revolution (of a record, engine, etc.) / reverend",
	rhino: "rhinoceros",
	ril: "really",
	Rhodie: "Rhodesian ridgeback / Rhodesian / Rhode Island red",
	Rolls: "a Rolls-Royce",
	ruck: "rucksack",
	rum: "rumbullion (obsolete)",
	"sales rep": "sales representative",
	"San Fran": "San Francisco",
	sarge: "sergeant",
	"sarky (UK)": "sarcastic",
	Satch: "Joe Satriani",
	sax: "saxophone",
	schizo: "schizophrenic",
	Scottie: "Scottish Terrier",
	scrum: "scrummage  (now mostly used in rugby football)",
	"Sea-Tac": "Seattle-Tacoma",
	sec: "second / secant",
	"Semper Fi!": "Semper Fidelis",
	sig: "significant (figures) / signal / (Internet) signature",
	sim: "simulation",
	sis: "sister",
	soph: "sophomore",
	sosh: "social (in the context of social security number)",
	spats: "spatterdashes",
	spec: "specialist / specification / speculation",
	specs: "specifications / spectacles",
	sperm: "spermaceti / spermatozoön",
	staph: "staphylococcus",
	stat: "statim (borrowed from Latin)",
	stats: "statistics",
	steno: "stenographer",
	stereo: "stereophony",
	strep: "streptococcus",
	stude: "student",
	sub: "subaltern / subeditor / subsidiary / sublieutenant / submarine / subordinate / subscriber / (especially as subs) subscription / subsistence money (an advance payment) / substitute / subway",
	sum: "summarize",
	"sus (or suss)": "suspect",
	sush: "sushi",
	"sync or synch": "synchronization / syncopation",
	synth: "synthesizer",
	syph: "syphilis",
	tab: "tabulation",
	tan: "tangent",
	tarp: "tarpaulin",
	"taxi or taxicab": "taximeter cabriolet",
	tech: "technician / technology",
	techno: "technology",
	teddy: "teddy bear",
	teen: "teenager, teenage",
	"tele or telly": "television",
	terb: "terrible",
	titfer: "tit for tat (hat)",
	tog: "obsolete togeman, from obsolete French togue, cloak, from Latin toga, garment",
	trad: "tradition(al)",
	tranny: "transmission / transsexual or transgender (slur/offensive) / transistor radio (obsolete)",
	tranq: "tranquilizer",
	trans: "transgender",
	trig: "trigonometry",
	Trot: "Trotskyite",
	"turp, turps": "turpentine",
	tux: "tuxedo",
	twofer: "two for one, two for the price of one",
	typo: "typographical error",
	undies: "underwear",
	uni: "university",
	unicam: "(unicameral) legislature (Nebraska, United States only)",
	"vag, vadge": "vagina",
	veg: "vegetate",
	"veg or veggie": "vegetable / vegetarian or vegan",
	vet: "veterinarian / veteran",
	Westie: "West Highland Terrier",
	Wisc: "Wisconsin",
	"women's lib": "women's liberation",
	xolo: "xoloitzcuintli",
	Yank: "Yankee",
	Yid: "Jew (Yiddisher; offensive)",
	zep: "zeppelin",
	Zin: "Zinfandel",
	zinco: "zincograph",
	zoo: "zoological garden",
};
